[workspace]
resolver = "2"

members = [
  "main",
  "web-htmx",
]

[workspace.dependencies]
axum = { version = "0.6.20" }
serde = { version = "1.0.188" }
serde_json = { version = "1.0.107" }
tokio = { version = "1.32.0" }
tower = { version = "0.4.13" }
tower-http = { version = "0.4.4" }
tower-livereload = { version = "0.8.1" }
render = { version = "0.3.1" }
