version: '3'
services:
  auth_mongo:
    ports:
      - "27017:27017"
    container_name: auth-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    image: mongo:7.0.4
    volumes: 
      - auth_mongo_data:/data/db

volumes:
  auth_mongo_data:
      
