services:
  - name: wallchart
    type: web
    env: rust
    region: ohio
    # Install bun, build client, then build rust app
    buildCommand: |
      curl -fsSL https://bun.sh/install | bash 
      export BUN_INSTALL="$HOME/.bun"
      export PATH=$BUN_INSTALL/bin:$PATH
      ./build-client.sh
      cargo build --release
    startCommand: cargo run --release
    healthCheckPath: /healthcheck
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: OUT_DIR
        value: "out"
      - key: AUTH_MONGO_DB_URL
        fromService:
          type: pserv
          name: auth-mongo
          property: connectionString
          
  - type: pserv
    name: auth-mongo
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
