//##PLOP COMPONENT MOD##
pub mod add_location_form;
pub mod worker_detail;
pub mod login_form;
pub mod add_worker_form;
pub mod appshell;
pub mod logo;
pub mod nav;
pub mod not_found_message;
pub mod wallchart;
