//##PLOP COMPONENT MOD##
pub mod add_location_form;
pub mod add_shift_form;
pub mod add_worker_form;
pub mod appshell;
pub mod assign_shift_form;
pub mod login_form;
pub mod logo;
pub mod nav;
pub mod not_found_message;
pub mod page;
pub mod simple_form;
pub mod wallchart;
pub mod worker_profile_fieldset;
pub mod workers;
